### ISSUE TITLE
WAF Policy

### ISSUE THREAD

**Issue by gamlielalon1983** [intelequia/letsencrypt-aw#3] opened 2020-03-15 14:47 UTC
Hi 
when working with waf policy im not able to update certificate 
Set-AzureRmApplicationGateway : Firewall policy /subscriptions/c7ca268c-3d6e-4e55-81e6-89ad0105ddeb/resourceGroups/Lever

/providers/Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies/wafwebhostingpolicy cannot 

be removed from Application Gateway, changing from one firewall policy to another is permitted.

At line:116 char:1

+ Set-AzureRmApplicationGateway -ApplicationGateway $appgw

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : CloseError: (:) [S 
  et-AzureRmApplicationGateway], CloudException
   + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.SetAzureApplicationGatewayCommand

**Comment by chucklebrother** [comment] 2020-09-13 13:56
I too am seeing this issue, I'm fairly sure I was not when we didn't have a WAF policy on the AppGW.

Interestingly if I open up an azure shell and do the following with line 114 and 116 (skipping thee intermediate line that is updating the certificate config for the app GW):

$appgw = Get-AzureRmApplicationGateway -ResourceGroupName $AGResourceGroupName -Name $AGName

Set-AzureRmApplicationGateway -ApplicationGateway $appgw

things work as expected (the gateway is set to the settings just extracted from its current config).

if I modify the script and comment out line 115 so the script is essential performing the same thing. I get the same error.

next thing to do is see if I can run the script in the azure cloud shell but substituting in the parameters I am using in my runbook schedule

If it works in the cloud shell but not in my automation account that will be interesting. If i get around to testing this I will add an update.

**Comment by chucklebrother** [comment] 2020-09-13 15:23
Also noticed that there is an open pull request for this script using Az cdmdlets rather than depreciated AzureRM cmdlets and this was fixing the other open issue. Given that id been mulling over seeing if the az cmdlets worked better I thought id give it a go.

PR:
https://github.com/intelequia/letsencrypt-aw/pull/4

From:
https://github.com/Mik4sa/letsencrypt-aw

After some somewhat confusing messing around with my automation account to migrate it to support the AZ modules* I was able to run the Az version of the script and this successfully updated my certificate against my AppGW with its WAF configuration.

I'm not sure this isnt an MS bug, as I don't believe AzureRM should be failing like this as they AzureRM modules are still installed in automation accounst be default.
However given that the script with the az cmdlets works as intended I am not sure I'll have the time or inclination to pursue this further.

Thanks Mik4sa for the updated script.

*(MS admonish you to never use AzureRM and AZ in the same automation account, but their instructions for migrating and removing the AzureRM default module were not obvious, to me at least)

**Comment by davidjrh** [comment] 2020-09-13 17:24
Given that the new modules are the AZ based, the pull request made by @Mik4sa fixes this issue. Thanks @Mik4sa again. 

https://github.com/intelequia/letsencrypt-aw/blob/master/letsencryptaw_v2.ps1

**Closed as completed by davidjrh** 2020-09-13 17:24 UTC
